# Generated by Django 4.2.5 on 2023-09-20 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppExercicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 22, 52, 31, 699896, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 22, 52, 31, 699896, tzinfo=datetime.timezone.utc)),
        ),
    ]
